//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SketchFull.Resourses.Strings {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SketchFull.Resourses.Strings.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Perform alignment.
        /// </summary>
        public static string Aligment {
            get {
                return ResourceManager.GetString("Aligment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attension.
        /// </summary>
        public static string Attension {
            get {
                return ResourceManager.GetString("Attension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete unnecessary sketches while updating.
        /// </summary>
        public static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reinforcement direction.
        /// </summary>
        public static string Dialog1 {
            get {
                return ResourceManager.GetString("Dialog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reinforcement layer.
        /// </summary>
        public static string Dialog2 {
            get {
                return ResourceManager.GetString("Dialog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Major.
        /// </summary>
        public static string Dialog3 {
            get {
                return ResourceManager.GetString("Dialog3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minor.
        /// </summary>
        public static string Dialog4 {
            get {
                return ResourceManager.GetString("Dialog4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Top.
        /// </summary>
        public static string Dialog5 {
            get {
                return ResourceManager.GetString("Dialog5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bottom.
        /// </summary>
        public static string Dialog6 {
            get {
                return ResourceManager.GetString("Dialog6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на run2.htm.
        /// </summary>
        public static string HelpSection {
            get {
                return ResourceManager.GetString("HelpSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This view is not suitable for placing sketches..
        /// </summary>
        public static string Info1 {
            get {
                return ResourceManager.GetString("Info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to create a temporary view for sketching. \n Select a different view to place the sketch..
        /// </summary>
        public static string Info10 {
            get {
                return ResourceManager.GetString("Info10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are trying to create too many sketches at once. \n This will take a long time. We recommend that you select fewer members for sketching. \n Continue creating?.
        /// </summary>
        public static string Info2 {
            get {
                return ResourceManager.GetString("Info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No rebars for sketching..
        /// </summary>
        public static string Info3 {
            get {
                return ResourceManager.GetString("Info3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to determine the insertion point for sketches. Assign a work plane..
        /// </summary>
        public static string Info4 {
            get {
                return ResourceManager.GetString("Info4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The sketch insertion point outside the drawing area. Sketch: will not be visible or partially hidden..
        /// </summary>
        public static string Info5 {
            get {
                return ResourceManager.GetString("Info5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The sketch will not be visible. Check the visibility settings of the LINE CATEGORIES..
        /// </summary>
        public static string Info6 {
            get {
                return ResourceManager.GetString("Info6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No sketches for renovation..
        /// </summary>
        public static string Info7 {
            get {
                return ResourceManager.GetString("Info7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For this reinforcement: Sketch detected in a different view. \n We recommend using standard copy. \n A new independent sketch type will be created. Create a new sketch?.
        /// </summary>
        public static string Info8 {
            get {
                return ResourceManager.GetString("Info8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For this reinforcement: there are already multiple instances of the sketch in the current view. /n ALL SKETCHES FROM ALL VIEWS will be deleted and a new sketch type created. /n Create a new sketch?.
        /// </summary>
        public static string Info9 {
            get {
                return ResourceManager.GetString("Info9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use as prefix.
        /// </summary>
        public static string Label1 {
            get {
                return ResourceManager.GetString("Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на coeff..
        /// </summary>
        public static string LabelScale {
            get {
                return ResourceManager.GetString("LabelScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scale.
        /// </summary>
        public static string LabelScale0 {
            get {
                return ResourceManager.GetString("LabelScale0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line types.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tag for sketch.
        /// </summary>
        public static string NameBox1 {
            get {
                return ResourceManager.GetString("NameBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reinforcement sketch-drawing.
        /// </summary>
        public static string NameImage {
            get {
                return ResourceManager.GetString("NameImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reinforcement: tools.
        /// </summary>
        public static string NamePanel {
            get {
                return ResourceManager.GetString("NamePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \\Resources\\Help\\Sketch reinforcement.chm.
        /// </summary>
        public static string pathToHelp {
            get {
                return ResourceManager.GetString("pathToHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c:\\ProgramData\\Autodesk\\ApplicationPlugins\\ADNPlugin-SketchReinforcement.bundle\\Contents\\Resources\\Help\\Sketch reinforcement.chm.
        /// </summary>
        public static string PathToHelpFile {
            get {
                return ResourceManager.GetString("PathToHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sketching process.
        /// </summary>
        public static string Process1 {
            get {
                return ResourceManager.GetString("Process1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The process of placing sketches.
        /// </summary>
        public static string Process2 {
            get {
                return ResourceManager.GetString("Process2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The process of updating all sketches in a project.
        /// </summary>
        public static string Process3 {
            get {
                return ResourceManager.GetString("Process3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process for updating sketches in the current view.
        /// </summary>
        public static string Process4 {
            get {
                return ResourceManager.GetString("Process4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Rebar or Area or Path reinforcement.
        /// </summary>
        public static string SelectRebar {
            get {
                return ResourceManager.GetString("SelectRebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Specify sketch insertion point.
        /// </summary>
        public static string ShowInsertPoint {
            get {
                return ResourceManager.GetString("ShowInsertPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Problem.
        /// </summary>
        public static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Structural area reinforcement.
        /// </summary>
        public static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rebar sketching.
        /// </summary>
        public static string Title3 {
            get {
                return ResourceManager.GetString("Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Ø and total length.
        /// </summary>
        public static string TotalLength {
            get {
                return ResourceManager.GetString("TotalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update all.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update view.
        /// </summary>
        public static string UpdateView {
            get {
                return ResourceManager.GetString("UpdateView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add-in is for version not older 2023.
        /// </summary>
        public static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
    }
}
